// LAN server for the CLI (`ainess serve`): node:http + SSE, same protocol as src-tauri/src/remote.rs.
import * as http from "node:http";
import * as zlib from "node:zlib";
import * as os from "node:os";
import type { Transport } from "./transport";
import { remoteUrl } from "./remote";
import { translateNow } from "@/i18n/useT";
// Generated by `npm run build:remote` (see vite.remote.config.ts): the whole React page
// in one file. Relative on purpose: it lives outside `src/`, so the `@` alias does not reach it.
import remoteHtml from "../../dist-remote/index.html?raw";
// What an installed app needs beside the page (see src/remote/sw.js). Plain files, embedded the
// same way, so the CLI's server answers exactly what the app's does.
import manifestJson from "../../src/remote/public/manifest.webmanifest?raw";
import serviceWorkerJs from "../../src/remote/public/sw.js?raw";
import iconPngBase64 from "../../src/remote/public/icon.png?inline";

type Handler = (cmd: { id: string; action: string; payload: Record<string, unknown> }) => Promise<Record<string, unknown>>;

let server: http.Server | null = null;
let token = "";
let url = "";
let ip = "";
let lastSnapshot: unknown = null;
let handler: Handler | null = null;
const clients = new Set<http.ServerResponse>();

/** First non-internal IPv4 address (what the phone can reach on the WiFi). */
export function localIp(): string {
  for (const list of Object.values(os.networkInterfaces())) {
    for (const i of list ?? []) {
      if (i.family === "IPv4" && !i.internal) return i.address;
    }
  }
  return "127.0.0.1";
}

function authorized(req: http.IncomingMessage, reqUrl: URL): boolean {
  const q = reqUrl.searchParams.get("token");
  const h = req.headers.authorization;
  const bearer = h && h.startsWith("Bearer ") ? h.slice(7) : undefined;
  return !!token && (q === token || bearer === token);
}

function json(res: http.ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" });
  res.end(JSON.stringify(body));
}

function readBody(req: http.IncomingMessage): Promise<Record<string, unknown>> {
  return new Promise((resolve) => {
    let data = "";
    req.on("data", (c) => { data += c; if (data.length > 1_000_000) req.destroy(); });
    req.on("end", () => { try { resolve(data ? JSON.parse(data) : {}); } catch { resolve({}); } });
    req.on("error", () => resolve({}));
  });
}

const ACTIONS: Record<string, string> = {
  "/api/prompt": "prompt",
  "/api/instruct": "instruct",
  "/api/stop": "stop",
  "/api/approve": "approve",
  "/api/chat": "chat",
  "/api/task": "task",
  "/api/answer": "answer",
};

/** Whether the client asked for gzip; one that did not gets the page as it is. */
function acceptsGzip(req: http.IncomingMessage): boolean {
  const header = req.headers["accept-encoding"];
  const value = Array.isArray(header) ? header.join(",") : header ?? "";
  return value.toLowerCase().split(",").some(part => part.trim().startsWith("gzip"));
}

let compressedPage: Buffer | undefined;
function gzippedPage(): Buffer {
  compressedPage ??= zlib.gzipSync(remoteHtml);
  return compressedPage;
}

async function onRequest(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
  const reqUrl = new URL(req.url || "/", "http://localhost");
  const path = reqUrl.pathname;

  // The page goes out to whoever asks: it holds no data (that is what /api/ is for, and that stays
  // behind the token) and it is what asks for the token when the link did not bring one. Gated, a
  // phone opening the bare address got a raw {"error":translateNow("remote.err.invalidToken")} with nowhere to type it.
  if (req.method === "GET" && path === "/") {
    // A megabyte of single-file bundle, and it travels: compressed it is about a third. Same page
    // every time, so it is compressed once (see src-tauri/src/remote.rs, which does the same).
    if (acceptsGzip(req)) {
      res.writeHead(200, {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Encoding": "gzip",
        "Cache-Control": "no-store",
        Vary: "Accept-Encoding",
      });
      res.end(gzippedPage());
      return;
    }
    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" });
    res.end(remoteHtml);
    return;
  }
  // Open, like the page: a manifest behind a token is one the browser cannot read, and what you
  // install to the home screen would be a bookmark instead of an app.
  if (req.method === "GET" && path === "/manifest.webmanifest") {
    res.writeHead(200, { "Content-Type": "application/manifest+json; charset=utf-8", "Cache-Control": "no-store" });
    res.end(manifestJson);
    return;
  }
  if (req.method === "GET" && path === "/sw.js") {
    // `no-store`: the browser keeps its own copy of a worker, and this is what lets an update of
    // the app reach a phone that already installed one.
    res.writeHead(200, { "Content-Type": "text/javascript; charset=utf-8", "Cache-Control": "no-store" });
    res.end(serviceWorkerJs);
    return;
  }
  if (req.method === "GET" && path === "/icon.png") {
    res.writeHead(200, { "Content-Type": "image/png", "Cache-Control": "max-age=86400" });
    res.end(Buffer.from(iconPngBase64.split(",")[1] ?? "", "base64"));
    return;
  }

  if (!authorized(req, reqUrl)) { json(res, 401, { error: translateNow("remote.err.invalidToken") }); return; }
  if (req.method === "GET" && path === "/api/state") {
    const snap = handler ? await handler({ id: "state", action: "state", payload: {} }) : lastSnapshot;
    json(res, 200, snap ?? {});
    return;
  }
  if (req.method === "GET" && path === "/api/events") {
    res.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-store", "Connection": "keep-alive" });
    res.write(":ok\n\n");
    const snap = handler ? await handler({ id: "state", action: "state", payload: {} }) : lastSnapshot;
    if (snap) res.write(`event: state\ndata: ${JSON.stringify(snap)}\n\n`);
    clients.add(res);
    const ping = setInterval(() => { try { res.write("event: ping\ndata: {}\n\n"); } catch { /* closed */ } }, 20000);
    req.on("close", () => { clearInterval(ping); clients.delete(res); });
    return;
  }
  if (req.method === "POST" && ACTIONS[path]) {
    if (!handler) { json(res, 503, { error: "Servidor sin orquestador" }); return; }
    const payload = await readBody(req);
    const result = await handler({ id: crypto.randomUUID(), action: ACTIONS[path], payload });
    json(res, result.error ? 400 : 200, result);
    return;
  }
  json(res, 404, { error: translateNow("remote.notFound") });
}

export const nodeRemote: Pick<Transport, "remoteStart" | "remoteStop" | "remoteStatus" | "remotePushState" | "onRemoteCommand"> = {
  remoteStart: (port, tok) => new Promise((resolve, reject) => {
    if (server) { resolve({ url, ip }); return; }
    token = tok;
    const s = http.createServer((req, res) => { void onRequest(req, res); });
    s.on("error", (err: NodeJS.ErrnoException) => {
      server = null;
      reject(new Error(err.code === "EADDRINUSE" ? translateNow("remote.portBusy", { port }) : err.message));
    });
    s.listen(port, "0.0.0.0", () => {
      server = s;
      ip = localIp();
      url = remoteUrl(ip, port, token);
      resolve({ url, ip });
    });
  }),
  remoteStop: async () => {
    for (const c of clients) { try { c.end(); } catch { /* ignore */ } }
    clients.clear();
    await new Promise<void>((resolve) => { if (!server) return resolve(); server.close(() => resolve()); server = null; });
  },
  remoteStatus: async () => ({ running: !!server, url: server ? url : undefined, ip: server ? ip : undefined, clients: clients.size }),
  remotePushState: async (snapshot) => {
    lastSnapshot = snapshot;
    const line = `event: state\ndata: ${JSON.stringify(snapshot)}\n\n`;
    for (const c of clients) { try { c.write(line); } catch { clients.delete(c); } }
  },
  onRemoteCommand: async (h) => { handler = h; return () => { if (handler === h) handler = null; }; },
};
