import { Transport } from "./transport";

const TERMINALS_UNAVAILABLE = "Las terminales solo están disponibles en la app de escritorio";

// Used by the plain-browser preview (vite dev without Tauri): nothing can run or persist.
export const nullTransport: Transport = {
  spawnRun: async () => {},
  reapOrphans: async () => [],
  killRun: async () => false,
  onRunOutput: async () => () => {},
  onRunExit: async () => () => {},
  loadConfig: async () => null,
  saveConfig: async () => {},
  detectBinaries: async () => ({}),
  writeTextFile: async (path) => path,
  readTextFile: async () => null,
  exec: async (_program, _args, _cwd) => ({ code: null, stdout: "", stderr: "" }),
  httpPost: async () => { throw new Error("null transport"); },
  httpGet: async () => ({ status: 0, body: "" }),
  readHomeFile: async () => null,
  writeFileAbs: async () => {},
  writeFileBytes: async () => {},
  readFileAbs: async () => null,
  filesExistAbs: async () => [],
  storageStat: async () => null,
  portAvailable: async () => null,
  remoteStart: async () => { throw new Error("El acceso remoto no está disponible en el navegador"); },
  remoteStop: async () => {},
  remoteStatus: async () => ({ running: false, clients: 0 }),
  remotePushState: async () => {},
  onRemoteCommand: async () => () => {},
  setTrayEnabled: async () => {},
  logAppend: async () => {},
  logsDir: async () => "",
  openLogsDir: async () => { throw new Error("No disponible en el navegador"); },
  tunnelStart: async () => { throw new Error("El túnel no está disponible en el navegador"); },
  tunnelStop: async () => {},
  tunnelStatus: async () => ({ running: false }),
  tunnelDetect: async () => ({ cloudflared: null, ngrok: null }),
  ptySpawn: async () => { throw new Error(TERMINALS_UNAVAILABLE); },
  ptyWrite: async () => { throw new Error(TERMINALS_UNAVAILABLE); },
  ptyResize: async () => { throw new Error(TERMINALS_UNAVAILABLE); },
  ptyKill: async () => { throw new Error(TERMINALS_UNAVAILABLE); },
  ptyListShells: async () => [],
  onPtyOutput: async () => () => {},
  onPtyExit: async () => () => {},
  deleteFile: async () => {},
  repoWatchStart: async () => {},
  repoWatchStop: async () => {},
  onRepoChanged: async () => () => {},
};
